on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install
      - run: npm run -- elm make --optimize src/Main.elm
      - uses: actions/upload-artifact@v2
        with:
          path: index.html
          name: bartleby-${{ github.sha }}.html
  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: bartleby-${{ github.sha }}.html
          path: index.html
      - run: git config user.email '${{ github.actor }}@invalid'
      - run: git config user.name '@${{ github.actor }}'
      - run: git init
      - run: git checkout -b github-pages
      - run: git remote add origin git@github.com:${{ github.repository }}.git
      - run: git add index.html
      - run: git commit -m 'Automatic deploy of ${{ github.sha }}'
      - run: git push -fu origin github-pages
