on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/cache@v2
        with:
          key: ${{ hashFiles('package.json', 'elm.json') }}
          path: |
            elm-stuff
            node_modules
      - run: npm install --no-audit
      - run: npm run -- elm make --optimize src/Main.elm
      - uses: actions/upload-artifact@v2
        with:
          path: index.html
          name: bartleby-${{ github.sha }}.html
